export class Inbox {
    version: number
    id: number
    inboxReceiveFlag: number
    inboxOpenFlag: number
    inboxActionFlag: number
    inboxFinishFlag: number
    letterStatus1: number
    letterStatus2: number
    letterStatus3: number
    createdBy: number
    createdDate: string
    orderNo: number
    removedBy: number
    removedDate: string
    updatedBy: number
    updatedDate: string
    workflowId: number
    userProfileFolderId: number
    structureFolderId: number
    inboxFrom: string
    inboxTo: string
    inboxTitle: string
    inboxSendDate: string
    inboxReceiveDate: string
    inboxReceiveDateDefine: string
    inboxOpenDate: string
    inboxOpenDateDefine: string
    inboxActionDate: string
    inboxActionDateDefine: string
    inboxFinishDate: string
    inboxFinishDateDefine: string
    moduleId: number
    linkId: number
    linkId2: number
    linkType: string
    inboxStr01: string
    inboxStr02: string
    inboxStr03: string
    inboxStr04: string
    inboxDate01: string
    inboxDate02: string
    inboxDescription: string
    inboxNote: string
    inboxKey: string
    inboxApprove: number
    inboxApproveStatus: number
    
    isFinished: boolean
    isCanceled: boolean
    inboxSpeed: number
}