export class Outbox {
    version: number
    id: number
    outboxReceiveFlag: number
    outboxOpenFlag: number
    outboxActionFlag: number
    outboxFinishFlag: number
    letterStatus1: number
    letterStatus2: number
    letterStatus3: number
    createdBy: number
    createdDate: string
    orderNo: number
    removedBy: number
    removedDate: string
    updatedBy: number
    updatedDate: string
    workflowId: number
    userProfileFolderId: number
    structureFolderId: number
    outboxFrom: string
    outboxTo: string
    outboxCc: string
    outboxTitle: string
    outboxSendDate: string
    outboxReceiveDate: string
    outboxReceiveDateDefine: string
    outboxOpenDate: string
    outboxOpenDateDefine: string
    outboxActionDate: string
    outboxActionDateDefine: string
    outboxFinishDate: string
    outboxFinishDateDefine: string
    moduleId: number
    linkId: number
    linkId2: number
    linkType: string
    outboxStr01: string
    outboxStr02: string
    outboxStr03: string
    outboxStr04: string
    outboxDate01: string
    outboxDate02: string
    outboxDescription: string
    outboxNote: string
    outboxApprove: number
    outboxSpeed: number

    isCanceled: boolean
}