export class Workflow {
    version: number
    id: number
    createdBy: number
    createdDate: string
    orderNo: number
    removedBy: number
    removedDate: string
    updatedBy: number
    updatedDate: string
    linkId: number
    linkId2: number
    linkId3: number
    workflowActionId: number
    workflowActionIdType: number
    workflowActionName: string
    workflowActionPosition: string
    workflowActionType: string
    workflowDescription: string
    workflowNote: string
    workflowTitle: string
    workflowStr01: string
    workflowStr02: string
    workflowStr03: string
    workflowStr04: string
    workflowDate01: string
    workflowDate02: string
    workflowDetail: string
}
