import { Document } from './document.model'
export const DOCUMENTS: Document[] = [


      {
          version:1,
      "id": 15,
      "createdDate": "17/03/2560 12:35:06",
      "createdBy": 1,
      "removedDate": "",
      "removedBy": 0,
      "updatedDate": "20/03/2560 13:32:36",
      "updatedBy": 1,
      "documentPublicDate": "",
      "documentExpireDate": "",
      "documentDate01": "",
      "documentDate02": "",
      "documentDate03": "",
      "documentDate04": "",
      "documentTypeId": 3,
      "documentName": "การวิเคราะห์ผลการดำเนินงานและเป้าหมายของปีก่อน",
      "documentPublicStatus": null,
      "documentFolderId": 134,
      "documentFloat01": 0,
      "documentFloat02": 0,
      "documentVarchar01": null,
      "documentVarchar02": null,
      "documentVarchar03": null,
      "documentVarchar04": null,
      "documentVarchar05": null,
      "documentVarchar06": null,
      "documentVarchar07": null,
      "documentVarchar08": null,
      "documentVarchar09": null,
      "documentVarchar10": null,
      "documentText01": null,
      "documentText02": null,
      "documentText03": null,
      "documentText04": null,
      "documentText05": null,
      "documentInt01": 0,
      "documentInt02": 0,
      "documentInt03": 0,
      "documentInt04": 0,
      "dmsDocumentIntComma": 0,
      "dmsDocumentSec": 0,
      "expType": null,
      "fullPathName":'',
      "expNumber": 0,
      "wfTypeId":0,
      "userProfileCreate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileUpdate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileDel": null
    },
    {
        version:1,
      "id": 16,
      "createdDate": "17/03/2560 12:38:18",
      "createdBy": 1,
      "removedDate": "",
      "removedBy": 0,
      "updatedDate": "20/03/2560 13:32:48",
      "updatedBy": 1,
      "documentPublicDate": "",
      "documentExpireDate": "",
      "documentDate01": "",
      "documentDate02": "",
      "documentDate03": "",
      "documentDate04": "",
      "documentTypeId": 3,
      "documentName": "กำหนดแผนปฏิบัติการ เป้าหมายประจำปี โดยพิจารณาปัจจัยภายใน",
      "documentPublicStatus": null,
      "documentFolderId": 134,
      "documentFloat01": 0,
      "documentFloat02": 0,
      "documentVarchar01": null,
      "documentVarchar02": null,
      "documentVarchar03": null,
      "documentVarchar04": null,
      "documentVarchar05": null,
      "documentVarchar06": null,
      "documentVarchar07": null,
      "documentVarchar08": null,
      "documentVarchar09": null,
      "documentVarchar10": null,
      "documentText01": null,
      "documentText02": null,
      "documentText03": null,
      "documentText04": null,
      "documentText05": null,
      "documentInt01": 0,
      "documentInt02": 0,
      "documentInt03": 0,
      "documentInt04": 0,
      "dmsDocumentIntComma": 0,
      "dmsDocumentSec": 0,
      "expType": null,
      "fullPathName":'',
      "expNumber": 0,
      "wfTypeId":0,
      "userProfileCreate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileUpdate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileDel": null
    },
    {
        version:1,
      "id": 17,
      "createdDate": "17/03/2560 12:42:17",
      "createdBy": 1,
      "removedDate": "",
      "removedBy": 0,
      "updatedDate": "20/03/2560 13:33:00",
      "updatedBy": 1,
      "documentPublicDate": "",
      "documentExpireDate": "",
      "documentDate01": "",
      "documentDate02": "",
      "documentDate03": "",
      "documentDate04": "",
      "documentTypeId": 3,
      "documentName": "กำหนดแผนปฏิบัติการ เป้าหมายประจำปี โดยพิจารณาปัจจัยภายนอก",
      "documentPublicStatus": null,
      "documentFolderId": 134,
      "documentFloat01": 0,
      "documentFloat02": 0,
      "documentVarchar01": null,
      "documentVarchar02": null,
      "documentVarchar03": null,
      "documentVarchar04": null,
      "documentVarchar05": null,
      "documentVarchar06": null,
      "documentVarchar07": null,
      "documentVarchar08": null,
      "documentVarchar09": null,
      "documentVarchar10": null,
      "documentText01": null,
      "documentText02": null,
      "documentText03": null,
      "documentText04": null,
      "documentText05": null,
      "documentInt01": 0,
      "documentInt02": 0,
      "documentInt03": 0,
      "documentInt04": 0,
      "dmsDocumentIntComma": 0,
      "dmsDocumentSec": 0,
      "expType": null,
      "fullPathName":'',
      "expNumber": 0,
      "wfTypeId":0,
      "userProfileCreate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileUpdate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileDel": null
    },
    {
        version:1,
      "id": 18,
      "createdDate": "20/03/2560 13:35:40",
      "createdBy": 1,
      "removedDate": "",
      "removedBy": 0,
      "updatedDate": "20/03/2560 14:00:48",
      "updatedBy": 1,
      "documentPublicDate": "",
      "documentExpireDate": "",
      "documentDate01": "",
      "documentDate02": "",
      "documentDate03": "",
      "documentDate04": "",
      "documentTypeId": 3,
      "documentName": "แผนการใช้ทรัพยากร",
      "documentPublicStatus": null,
      "documentFolderId": 134,
      "documentFloat01": 0,
      "documentFloat02": 0,
      "documentVarchar01": null,
      "documentVarchar02": null,
      "documentVarchar03": null,
      "documentVarchar04": null,
      "documentVarchar05": null,
      "documentVarchar06": null,
      "documentVarchar07": null,
      "documentVarchar08": null,
      "documentVarchar09": null,
      "documentVarchar10": null,
      "documentText01": null,
      "documentText02": null,
      "documentText03": null,
      "documentText04": null,
      "documentText05": null,
      "documentInt01": 0,
      "documentInt02": 0,
      "documentInt03": 0,
      "documentInt04": 0,
      "dmsDocumentIntComma": 0,
      "dmsDocumentSec": 0,
      "expType": null,
      "fullPathName":'',
      "expNumber": 0,
      "wfTypeId":0,
      "userProfileCreate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileUpdate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileDel": null
    },
    {
         version:1,
      "id": 19,
      "createdDate": "20/03/2560 13:36:32",
      "createdBy": 1,
      "removedDate": "",
      "removedBy": 0,
      "updatedDate": "20/03/2560 14:00:51",
      "updatedBy": 1,
      "documentPublicDate": "",
      "documentExpireDate": "",
      "documentDate01": "",
      "documentDate02": "",
      "documentDate03": "",
      "documentDate04": "",
      "documentTypeId": 3,
      "documentName": "จัดสรรงบประมาณ",
      "documentPublicStatus": null,
      "documentFolderId": 134,
      "documentFloat01": 0,
      "documentFloat02": 0,
      "documentVarchar01": null,
      "documentVarchar02": null,
      "documentVarchar03": null,
      "documentVarchar04": null,
      "documentVarchar05": null,
      "documentVarchar06": null,
      "documentVarchar07": null,
      "documentVarchar08": null,
      "documentVarchar09": null,
      "documentVarchar10": null,
      "documentText01": null,
      "documentText02": null,
      "documentText03": null,
      "documentText04": null,
      "documentText05": null,
      "documentInt01": 0,
      "documentInt02": 0,
      "documentInt03": 0,
      "documentInt04": 0,
      "dmsDocumentIntComma": 0,
      "dmsDocumentSec": 0,
      "expType": null,
      "fullPathName":'',
      "expNumber": 0,
      "wfTypeId":0,
      "userProfileCreate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileUpdate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileDel": null
    }
   

]

export const DOCUMENTSEARCHS: Document[] = [
     {
          version:1,
      "id": 15,
      "createdDate": "17/03/2560 12:35:06",
      "createdBy": 1,
      "removedDate": "",
      "removedBy": 0,
      "updatedDate": "20/03/2560 13:32:36",
      "updatedBy": 1,
      "documentPublicDate": "",
      "documentExpireDate": "",
      "documentDate01": "",
      "documentDate02": "",
      "documentDate03": "",
      "documentDate04": "",
      "documentTypeId": 3,
      "documentName": "การวิเคราะห์ผลการดำเนินงานและเป้าหมายของปีก่อน",
      "documentPublicStatus": null,
      "documentFolderId": 134,
      "documentFloat01": 0,
      "documentFloat02": 0,
      "documentVarchar01": null,
      "documentVarchar02": null,
      "documentVarchar03": null,
      "documentVarchar04": null,
      "documentVarchar05": null,
      "documentVarchar06": null,
      "documentVarchar07": null,
      "documentVarchar08": null,
      "documentVarchar09": null,
      "documentVarchar10": null,
      "documentText01": null,
      "documentText02": null,
      "documentText03": null,
      "documentText04": null,
      "documentText05": null,
      "documentInt01": 0,
      "documentInt02": 0,
      "documentInt03": 0,
      "documentInt04": 0,
      "dmsDocumentIntComma": 0,
      "dmsDocumentSec": 0,
      "expType": null,
      "fullPathName":'',
      "expNumber": 0,
      "wfTypeId":0,
      "userProfileCreate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileUpdate": {
        "id": 1,
        "structure": {
          "id": 1,
          "name": "โครงสร้างหน่วยงาน",
          "detail": null,
          "code": null,
          "nodeLevel": 0,
          "parentId": 0,
          "parentKey": "฿1฿"
        },
        "fullName": "ผู้ดูแลระบบ",
        "email": null,
        "tel": null,
        "address": null,
        "position": null
      },
      "userProfileDel": null
    },
]
