import { Folder } from './folder.model'

export const FOLDERS1: Folder[] = [

  {
    version: 1,
    "id": 59,
    "folderType": "C",
    "folderParentId": 1,
    "folderParentType": "C",
    "folderParentKey": "฿1฿59฿",
    "folderOrderId": 59,
    "folderNodeLevel": 2,
    "createDate": "01/03/2560 16:08:51",
    "removeDate": "",
    "createBy": 1,
    "removeBy": 0,
    "upDateDate": "20/03/2560 11:51:13",
    "upDateBy": 1,
    "folderDescription": "ฝ่ายตรวจสอบภายใน",
    "folderName": "ฝ่ายตรวจสอบภายใน",
    "folderTypeExpire": "",
    "folderTypeExpireNumber": 0,
    "documentTypeId": 2,
    "iconColor": "#f93550",
    "isWfFolderFromType":"N",
    "icon": "dashboard",
    'userProfileCreate': {
      "id": 1,
      "structure": {
        "id": 1,
        "name": "โครงสร้างหน่วยงาน",
        "detail": null,
        "code": null,
        "nodeLevel": 0,
        "parentId": 0,
        "parentKey": "฿1฿"
      },
      "fullName": "ผู้ดูแลระบบ",
      "email": null,
      "tel": null,
      "address": null,
      "position": null
    },

    'userProfileUpdate': {
      "id": 1,
      "structure": {
        "id": 1,
        "name": "โครงสร้างหน่วยงาน",
        "detail": null,
        "code": null,
        "nodeLevel": 0,
        "parentId": 0,
        "parentKey": "฿1฿"
      },
      "fullName": "ผู้ดูแลระบบ",
      "email": null,
      "tel": null,
      "address": null,
      "position": null
    },
     dmsEmailUserPreExpire:"",
     dmsUserPreExpire:1,
     'dmsUserProfilePreExpire': {
      "id": 1,
      "structure": {
        "id": 1,
        "name": "",
        "detail": null,
        "code": null,
        "nodeLevel": 0,
        "parentId": 0,
        "parentKey": "฿1฿"
      },
      "fullName": "",
      "email": null,
      "tel": null,
      "address": null,
      "position": null
    },
  },
  // {
  //   version: 1,
  //   "id": 105,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿",
  //   "folderOrderId": 105,
  //   "folderNodeLevel": 2,
  //   "createDate": "03/03/2560 17:14:20",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 11:53:57",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายพัฒนาโครงการ 1",
  //   "folderName": "ฝ่ายพัฒนาโครงการ 1",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#f93550",
  //   "isWfFolderFromType":"N",
  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 106,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿106฿",
  //   "folderOrderId": 106,
  //   "folderNodeLevel": 2,
  //   "createDate": "03/03/2560 17:14:55",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 11:55:26",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายบริหารสินทรัพย์",
  //   "folderName": "ฝ่ายบริหารสินทรัพย์",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#f93550",

  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 110,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿110฿",
  //   "folderOrderId": 110,
  //   "folderNodeLevel": 2,
  //   "createDate": "06/03/2560 15:05:56",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:00:56",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายปรับปรุงและบำรุงรักษาชุมชน",
  //   "folderName": "ฝ่ายปรับปรุงและบำรุงรักษาชุมชน",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#f93550",
  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 140,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿140฿",
  //   "folderOrderId": 140,
  //   "folderNodeLevel": 2,
  //   "createDate": "20/03/2560 12:08:08",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:08:19",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายบริหารงานชุมชน 1",
  //   "folderName": "ฝ่ายบริหารงานชุมชน 1",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#f93550",
  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 141,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿141฿",
  //   "folderOrderId": 141,
  //   "folderNodeLevel": 2,
  //   "createDate": "20/03/2560 12:11:46",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายนโยบายและแผน",
  //   "folderName": "ฝ่ายนโยบายและแผน",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#f93550",
  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 142,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿142฿",
  //   "folderOrderId": 142,
  //   "folderNodeLevel": 2,
  //   "createDate": "20/03/2560 12:12:25",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายการบริหารการเงินและการลงทุน",
  //   "folderName": "ฝ่ายการบริหารการเงินและการลงทุน",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#f93550",
  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 143,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿143฿",
  //   "folderOrderId": 143,
  //   "folderNodeLevel": 2,
  //   "createDate": "20/03/2560 12:12:49",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายทรัพยาการบุคคล",
  //   "folderName": "ฝ่ายทรัพยาการบุคคล",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#f93550",
  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 144,
  //   "folderType": "C",
  //   "folderParentId": 1,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿144฿",
  //   "folderOrderId": 144,
  //   "folderNodeLevel": 2,
  //   "createDate": "20/03/2560 12:13:15",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "ฝ่ายกฎหมาย",
  //   "folderName": "ฝ่ายกฎหมาย",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 3,
  //   "iconColor": "#f93550",
  //   "icon": "dashboard",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 130,
  //   "folderType": "D",
  //   "folderParentId": 105,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿",
  //   "folderOrderId": 130,
  //   "folderNodeLevel": 3,
  //   "createDate": "03/03/2560 16:20:58",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:15:41",
  //   "upDateBy": 1,
  //   "folderDescription": "กองวิเคราะห์และบริหารการเงินโครงการ 1",
  //   "folderName": "กองวิเคราะห์และบริหารการเงินโครงการ 1",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 3,
  //   "iconColor": "#4ee832",
  //   "icon": "dns",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 131,
  //   "folderType": "D",
  //   "folderParentId": 105,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿131฿",
  //   "folderOrderId": 131,
  //   "folderNodeLevel": 3,
  //   "createDate": "03/03/2560 17:17:38",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:16:06",
  //   "upDateBy": 1,
  //   "folderDescription": "กองบริหารโครงการ 1",
  //   "folderName": "กองบริหารโครงการ 1",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 3,
  //   "iconColor": "#4ee832",
  //   "icon": "dns",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 132,
  //   "folderType": "D",
  //   "folderParentId": 105,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿132฿",
  //   "folderOrderId": 132,
  //   "folderNodeLevel": 3,
  //   "createDate": "17/03/2560 11:32:27",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:16:25",
  //   "upDateBy": 1,
  //   "folderDescription": "กองบริหารโครงการ 2",
  //   "folderName": "กองบริหารโครงการ 2",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 3,
  //   "iconColor": "#4ee832",
  //   "icon": "dns",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 133,
  //   "folderType": "D",
  //   "folderParentId": 105,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿133฿",
  //   "folderOrderId": 133,
  //   "folderNodeLevel": 3,
  //   "createDate": "17/03/2560 11:33:41",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:16:35",
  //   "upDateBy": 1,
  //   "folderDescription": "กองบริหารโครงการ 3",
  //   "folderName": "กองบริหารโครงการ 3",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 3,
  //   "iconColor": "#4ee832",
  //   "icon": "dns",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 145,
  //   "folderType": "D",
  //   "folderParentId": 105,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿145฿",
  //   "folderOrderId": 145,
  //   "folderNodeLevel": 3,
  //   "createDate": "20/03/2560 12:16:46",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "กองบริหารโครงการ 4",
  //   "folderName": "กองบริหารโครงการ 4",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#4ee832",
  //   "icon": "dns",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 146,
  //   "folderType": "D",
  //   "folderParentId": 105,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿146฿",
  //   "folderOrderId": 146,
  //   "folderNodeLevel": 3,
  //   "createDate": "20/03/2560 12:17:45",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "กองสาธารณูปโภคและสิ่งแวดล้อมโครงการ 1",
  //   "folderName": "กองสาธารณูปโภคและสิ่งแวดล้อมโครงการ 1",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#4ee832",
  //   "icon": "dns",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // }, {
  //   version: 1,
  //   "id": 134,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿134฿",
  //   "folderOrderId": 134,
  //   "folderNodeLevel": 4,
  //   "createDate": "17/03/2560 11:36:09",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 14:00:37",
  //   "upDateBy": 1,
  //   "folderDescription": "01. การเงิน งบประมาณ",
  //   "folderName": "01. การเงิน งบประมาณ",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 135,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿135฿",
  //   "folderOrderId": 135,
  //   "folderNodeLevel": 4,
  //   "createDate": "17/03/2560 11:36:39",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:22:20",
  //   "upDateBy": 1,
  //   "folderDescription": "02. คำสั่ง มติ ครม. ประกาศ ระเบียบ พรบ. พรก. พรฎ. คู่มือ",
  //   "folderName": "02. คำสั่ง มติ ครม. ประกาศ ระเบียบ พรบ. พรก. พรฎ. คู่มือ",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 136,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿136฿",
  //   "folderOrderId": 136,
  //   "folderNodeLevel": 4,
  //   "createDate": "17/03/2560 11:37:15",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:22:29",
  //   "upDateBy": 1,
  //   "folderDescription": "03 โต้ตอบทั่วไป ขอความร่วมมือ ข่าวสารประชาสัมพันธ์ หนังสือเวียน",
  //   "folderName": "03 โต้ตอบทั่วไป ขอความร่วมมือ ข่าวสารประชาสัมพันธ์ หนังสือเวียน",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 137,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿137฿",
  //   "folderOrderId": 137,
  //   "folderNodeLevel": 4,
  //   "createDate": "17/03/2560 11:38:22",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:23:00",
  //   "upDateBy": 1,
  //   "folderDescription": "04. บริหารทั่วไป",
  //   "folderName": "04. บริหารทั่วไป",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 138,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿138฿",
  //   "folderOrderId": 138,
  //   "folderNodeLevel": 4,
  //   "createDate": "17/03/2560 11:39:03",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:23:13",
  //   "upDateBy": 1,
  //   "folderDescription": "05. บริหารงานบุคคล",
  //   "folderName": "05. บริหารงานบุคคล",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 139,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿139฿",
  //   "folderOrderId": 139,
  //   "folderNodeLevel": 4,
  //   "createDate": "17/03/2560 11:39:34",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "20/03/2560 12:23:21",
  //   "upDateBy": 1,
  //   "folderDescription": "06. เบ็ดเตล็ด",
  //   "folderName": "06. เบ็ดเตล็ด",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 147,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿147฿",
  //   "folderOrderId": 147,
  //   "folderNodeLevel": 4,
  //   "createDate": "20/03/2560 12:23:38",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "07. ประชุม  ",
  //   "folderName": "07. ประชุม  ",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 148,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿148฿",
  //   "folderOrderId": 148,
  //   "folderNodeLevel": 4,
  //   "createDate": "20/03/2560 12:23:49",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "08. ทุนฝึกอบรม ดูงาน บรรยาย วิชาการ",
  //   "folderName": "08. ทุนฝึกอบรม ดูงาน บรรยาย วิชาการ",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 3,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 149,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿149฿",
  //   "folderOrderId": 149,
  //   "folderNodeLevel": 4,
  //   "createDate": "20/03/2560 12:24:00",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "09. วัสดุ ครุภัณฑ์ ที่ดิน และสิ่งก่อสร้าง   ",
  //   "folderName": "09. วัสดุ ครุภัณฑ์ ที่ดิน และสิ่งก่อสร้าง   ",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 150,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿150฿",
  //   "folderOrderId": 150,
  //   "folderNodeLevel": 4,
  //   "createDate": "20/03/2560 12:24:25",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "10. รายงาน สถิติ และแบบสอบถาม",
  //   "folderName": "10. รายงาน สถิติ และแบบสอบถาม",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // },
  // {
  //   version: 1,
  //   "id": 151,
  //   "folderType": "F",
  //   "folderParentId": 130,
  //   "folderParentType": "C",
  //   "folderParentKey": "฿1฿105฿130฿151฿",
  //   "folderOrderId": 151,
  //   "folderNodeLevel": 4,
  //   "createDate": "20/03/2560 12:24:37",
  //   "removeDate": "",
  //   "createBy": 1,
  //   "removeBy": 0,
  //   "upDateDate": "",
  //   "upDateBy": 1,
  //   "folderDescription": "11. โครงการ แผนงาน วิจัย ",
  //   "folderName": "11. โครงการ แผนงาน วิจัย ",
  //   "folderTypeExpire": "",
  //   "folderTypeExpireNumber": 0,
  //   "documentTypeId": 2,
  //   "iconColor": "#e6b800",
  //   "icon": "folder",
  //   'userProfileCreate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },

  //   'userProfileUpdate': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "โครงสร้างหน่วยงาน",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "ผู้ดูแลระบบ",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  //   dmsEmailUserPreExpire:"",
  //   dmsUserPreExpire:1,
  //    'dmsUserProfilePreExpire': {
  //     "id": 1,
  //     "structure": {
  //       "id": 1,
  //       "name": "",
  //       "detail": null,
  //       "code": null,
  //       "nodeLevel": 0,
  //       "parentId": 0,
  //       "parentKey": "฿1฿"
  //     },
  //     "fullName": "",
  //     "email": null,
  //     "tel": null,
  //     "address": null,
  //     "position": null
  //   },
  // }

]

