export class Search {
  version: number
  documentName: string
  createdDateForm: string
  createdDateTo: string
  createdBy: string
  updatedDateForm: string
  updatedDateTo: string
  updatedBy: string
  documentExpireDateForm: string
  documentExpireDateTo: string
  documentDate01Form: string
  documentDate01To: string
  documentDate02Form: string
  documentDate02To: string
  documentDate03Form: string
  documentDate03To: string
  documentDate04Form: string
  documentDate04To: string
  documentFloat01: number
  documentFloat02: number
  documentInt01: number
  documentInt02: number
  documentInt03: number
  documentInt04: number
  documentText01: string
  documentText02: string
  documentText03: string
  documentText04: string
  documentText05: string
  documentVarchar01: string
  documentVarchar02: string
  documentVarchar03: string
  documentVarchar04: string
  documentVarchar05: string
  documentVarchar06: string
  documentVarchar07: string
  documentVarchar08: string
  documentVarchar09: string
  documentVarchar10: string
  documentIntComma:number
  folderId: number
}