export class SarabanContent {
    version: number
    id: number
    createdBy: number
    createdDate: any
    orderNo: number
    removedBy: number
    removedDate: any
    updatedBy: number
    updatedDate: any
    wfContentFolderId: number
    wfContentContentPre: string
    wfContentContentYear: number
    wfContentContentNo: string
    wfContentContentNumber: number
    wfContentContentPoint: number
    wfContentContentDate: any
    wfContentContentTime: string
    wfContentBookPre: string
    wfContentBookYear: number
    wfContentBookNo: string
    wfContentBookNumber: number
    wfContentBookPoint: number
    wfContentBookDate: any
    wfContentFrom: string
    wfContentTo: string
    wfContentTitle: string
    wfContentSpeed: number
    wfContentSecret: number
    wfContentSpeedStr: string
    wfContentSecretStr: string
    wfContentDescription: string
    wfContentReference: string
    wfContentAttachment: string
    wfContentExpireDate: any
    wfContentOwnername: string
    wfDocumentId: number
    workflowId: number
    inboxId: number
    wfContentStr01: string
    wfContentStr02: string
    wfContentStr03: string
    wfContentStr04: string
    wfContentStr05: string
    wfContentStr06: string
    wfContentStr07: string
    wfContentStr08: string
    wfContentStr09: string
    wfContentStr10: string
    wfContentText01: string
    wfContentText02: string
    wfContentText03: string
    wfContentText04: string
    wfContentText05: string
    wfContentText06: string
    wfContentText07: string
    wfContentText08: string
    wfContentText09: string
    wfContentText10: string
    wfContentInt01: number
    wfContentInt02: number
    wfContentInt03: number
    wfContentInt04: number
    wfContentInt05: number
    wfContentInt06: number
    wfContentInt07: number
    wfContentInt08: number
    wfContentInt09: number
    wfContentInt10: number
    wfContentDate01: any
    wfContentDate02: any
    wfContentDate03: any
    wfContentDate04: any
    wfContentDate05: any
    wfContentDate06: any
    wfContentDate07: any
    wfContentDate08: any
    wfContentDate09: any
    wfContentDate10: any
    hasFinish: boolean
    commandTypeName: string
    isCanceled: boolean
    status: number
    numFileAttach: number
    finishByS: number
    cancelBy: number
    isKeeped: boolean
}