import { Position } from './position.model'

export const POSITIONS: Position[] = [
    {
        version: 1,
        id: 1,
        name: "เจ้าพนักงานการเงินและบัญชี",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 2,
        name: "เจ้าพนักงานธุรการ",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 3,
        name: "นักจัดการงานทั่วไป",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 4,
        name: "นักทรัพยากรบุคคล",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 5,
        name: "นักบัญชี",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 6,
        name: "นักประชาสัมพันธ์",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 7,
        name: "นักวิชาการคลัง",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 8,
        name: "นักวิชาการคอมพิวเตอร์",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 9,
        name: "นักวิชาการเงินและบัญชี",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 10,
        name: "นักวิชาการตรวจสอบภายใน",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 11,
        name: "นักวิชาการพัสดุ",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 12,
        name: "นิติกร",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 13,
        name: "ผู้เชี่ยวชาญเฉพาะด้าน",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 14,
        name: "ผู้เชี่ยวชาญ",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 15,
        name: "ผู้อำนวยการ",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 16,
        name: "เศรษฐกร",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 17,
        name: "เจ้าพนักงานการคลัง",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 18,
        name: "เจ้าพนักงานขับรถยนต์",
        nameEng: "Tester",
        nameExtra: null,
    },
    {
        version: 1,
        id: 19,
        name: "Senior Customer Relation Representative",
        nameEng: "Senior Customer Relation Representative",
        nameExtra: null,
    },
    {
        version: 1,
        id: 20,
        name: "Internal Support Supervisor",
        nameEng: "Internal Support Supervisor",
        nameExtra: null,
    },
    {
        version: 1,
        id: 21,
        name: "Assistant to CEO",
        nameEng: "Assistant to CEO",
        nameExtra: null,
    },
    {
        version: 1,
        id: 22,
        name: "Senior System Analyst",
        nameEng: "Senior System Analyst",
        nameExtra: null,
    },
]